
{% set data = load_setup_py_data() %}


package:
  name: btms_ui

  version: {{ data.get('version') }}


source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - btms_ui
  requires:
    - pytest

about:
  home: https://github.com/pcdshub/btms_ui
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: Beam Transport System Motion User Interface
